### ISSUE TITLE
type mismatches within if statements do not localize the error

### ISSUE THREAD

**Issue by avh4** [elm-lang/error-message-catalog#7] opened 2015-05-24 08:57 UTC
For this example:
```elm
type alias Model = { i:Int, s:String, x:Int }

foo : String -> Float -> Float -> Model -> Model
foo s f1 f2 m =
    if | m.s == s ->
            { m
            | i <- 0
            , x <- round <| m.i * (f1-f2)
            }
       | otherwise -> m
```

The following error is not helpful enough:
```
-- TYPE MISMATCH -------------------------------------------------------------- 

This expression is triggering a type mismatch.

 4| 
 5|     if | m.s == s ->
 6|             { m
 7|             | i <- 0
 8|             , x <- round <| m.i * (f1-f2)
 9|             }
10|        | otherwise -> m
11| 

To be more specific, as I infer all the types, I am seeing a conflict between
this type:

    Int

and this type:

    Float
```

A better message would highlight the fact that the problem is with the expression `m.i * (f1-f2)` on line 8.

**Comment by evancz** [comment] 2015-10-28 09:00
The 0.16 error message is pretty interesting:

![screen shot 2015-10-28 at 1 58 27 am](https://cloud.githubusercontent.com/assets/1658058/10783785/6f477b34-7d17-11e5-8432-26c821b978dc.png)

So this is the root error, just with more context and stuff. I think it makes sense to close this and maybe make a meta-issue along with #28 about only using information from type annotations *after* the entire body has been checked. In this case, the body is self-consistent, which is kind of weird!

**Comment by evancz** [comment] 2016-08-05 23:25
Things are different now. I think we should update the example in a new issue if the problem is the same.

**Closed** 2016-08-05 23:24 UTC
Labels: types
