### ISSUE TITLE
Mismatched type annotations hide quality error messages

### ISSUE THREAD

**Issue by rtfeldman** [elm-lang/error-message-catalog#28] opened 2015-07-28 23:52 UTC
I've made this mistake many times, but it only just occurred to me what the common thread was between the errors.

Suppose I have this code:

```elm
brokenFunction : a -> String
brokenFunction foo =
    fourArgFunction 1 2 3

fourArgFunction : Int -> Int -> Int -> Int -> String
fourArgFunction one two three four =
    toString (one + two + three + four)
```

The error message I get is:

```
The type annotation for `brokenFunction` does not match its definition.

2| brokenFunction : a -> b -> String

As I infer the type of values flowing through your program, I see a conflict
between these two types:

    String

    Int -> String
```

The real problem, though, is that I've forgotten to pass a fourth argument to `fourArgumentFunction`.

This comes up a lot when I add an argument to a function, update some of its call sites, but then forget to update other call sites. I often end up confused because the error message mentions the caller but not the callee, so whenever I've made changes to both functions, the message leads me to presume one of my changes to the caller is the culprit, and I go down the wrong path.

A more helpful error message could notice the pattern of "caller was supposed to return `foo` but instead returned `a -> foo` as a result of a curried call to a function that takes `a` as its last argument" and point that out to me, e.g.

```
The type annotation for `brokenFunction` does not match its definition.

2| brokenFunction : a -> b -> String

As I infer the type of values flowing through your program, I see a conflict
between these two types:

    String

    Int -> String

Did you mean to call `fourArgFunction` with only 3 arguments?
It needs 4 arguments to be fully applied.
```

**Comment by evancz** [comment] 2015-07-29 00:00
Have you seen the error message when there is no type annotation? I have been writing some Elm today, and I think the problem is "bad messages when type annotations don't match". This is one of many examples of that.

I'd like to close this issue in favor of that. Is there an existing issue about it? If not, can you open one?

**Comment by evancz** [comment] 2015-07-29 00:02
Oops, did not mean to close. I took a look around, and this might be the first good example of the general problem. I'll just change the title!

**Comment by rtfeldman** [comment] 2015-07-29 00:08
Makes sense to me! :+1:

**Comment by rtfeldman** [comment] 2015-07-29 00:13
@evancz Here's what I see if I remove annotations (but add another call to trigger the error via inference):

```elm
import Html exposing (text)

brokenFunction foo =
    fourArgFunction 1 2 3

fourArgFunction one two three four =
    toString (one + two + three + four)
    

main =
    text (brokenFunction 1)
```

Error message:

```
The 1st argument to function `text` has an unexpected type.

11|     text (brokenFunction 1)

As I infer the type of values flowing through your program, I see a conflict
between these two types:

    String

    number -> String
```

So it's actually worse without the annotations, because now it's reporting about the caller of the offending caller instead of the offender itself. :crying_cat_face:

**Comment by evancz** [comment] 2015-07-29 00:23
I realized after I wrote to you that things would go through with inference, but just do something other than expected. I have an idea of how to improve messages when the given type annotation causes a conflict though. Got enough data to make that happen now.

**Comment by rtfeldman** [comment] 2015-07-29 00:26
Awesome!

**Comment by kitofr** [comment] 2015-11-23 21:29
Oh, I just ran into the same problem as above today. Once that was fixed I ended up with:

```
As I infer the type of values flowing through your program, I see a conflict
between these two types:

    Model

    Model
```

Don't know if they are related (need to understand the problem first) but the error message could help me out more here I suppose.

**Comment by evancz** [comment] 2015-11-23 23:16
@kitofr, can you try this with 0.16? If there are still issues, please open a *new* issue with a http://sscce.org. We can't do anything with an error message if we can't see the code that produced it!

**Comment by kitofr** [comment] 2015-11-24 09:23
@evancz I sure can do!

**Comment by kitofr** [comment] 2015-11-24 11:12
upgraded to 0.16 and the issue was gone

**Comment by evancz** [comment] 2016-08-10 05:12
Tracking in #154

**Closed by evancz** 2016-08-10 05:12 UTC
Labels: types

**Comment by evancz** [comment] 2016-09-20 22:31
Made progress. Currently looks like this:

![screen shot 2016-09-20 at 3 30 02 pm](https://cloud.githubusercontent.com/assets/1658058/18691182/3014f4e0-7f47-11e6-8519-e4f7dfad75d7.png)
