### ISSUE TITLE
Confusing message, inference beats annotation?

### ISSUE THREAD

**Issue by glenjamin** [elm-lang/error-message-catalog#115] opened 2016-05-02 19:13 UTC
Hello, sorry if this is a dupe - I'm brand new to elm so I'm not quite sure what terms to use when searching.

I was changing the elm architecture part 3 to include the ID of each counter on the page, when I made a mistake:

``` elm
viewCounter : Signal.Address Action -> ( ID, Counter.Model ) -> Html
viewCounter address ( id, model ) =
  div
    []
    [ (text id)
    , Counter.view (Signal.forwardTo address (Modify id)) model
    ]
```

The mistake is that I've failed to convert the `id` param into the string needed by `text`.

However, the build error is:

```
-- TYPE MISMATCH ------------------------------------------- ././CounterList.elm

The argument to function `Modify` is causing a mismatch.

96│                                               Modify id)
                                                         ^^
Function `Modify` is expecting the argument to be:

    Int

But it is:

    String

Detected errors in 1 module.
```

Whereas I'd expect to get the error against the `text` call.

**Comment by jvoigtlaender** [comment] 2016-05-03 05:31
It is indeed a duplicate. For example of https://github.com/elm-lang/error-message-catalog/issues/110, but there's also others already.

**Comment by rtfeldman** [comment] 2016-07-19 05:19
Closing as duplicate of #110. Thanks!

**Closed as completed by rtfeldman** 2016-07-19 05:19 UTC
