### ISSUE TITLE
No line number or example for whitespace expression in case expr

### ISSUE THREAD

**Issue by homburg** [elm-lang/error-message-catalog#102] opened 2016-03-23 16:58 UTC
This code

``` elm
f : String -> String
f str =
    case str of 
        "" -> ""
        _ ->


```

produces and error without any line number or indication of place:

```
-- SYNTAX PROBLEM ----------------------------------------------------- Test.elm

I need whitespace, but got stuck on what looks like a new declaration. You are
either missing some stuff in the declaration above or just need to add some
spaces here:


I am looking for one of the following things:

    whitespace

Detected errors in 1 module.                                        
```

**Comment by rtfeldman** [comment] 2016-07-20 17:09
Thanks for reporting this! It's a duplicate of https://github.com/elm-lang/error-message-catalog/issues/96 so I'm going to close it in order to have one fewer issue to track.

**Closed as completed by rtfeldman** 2016-07-20 17:09 UTC
Labels: parser
