### ISSUE TITLE
Error message for tabs/spaces

### ISSUE THREAD

**Issue by laszlopandy** [elm-lang/error-message-catalog#56] opened 2015-11-10 18:50 UTC
If you create a valid-looking Elm file that uses tabs instead of spaces it gives you an error "expecting whitespace". I would be nice if it said "use spaces instead of tabs".

This came up because tabs are the default in IntelliJ.

```
## ERRORS in Test.elm ##########################################################

-- SYNTAX PROBLEM ----------------------------------------------------- Test.elm

I ran into something unexpected when parsing your code!

4|     show "Hello"
   ^
I am looking for one of the following things:

    whitespace


Detected errors in 1 module. 
```

**Comment by rtfeldman** [comment] 2015-11-10 22:55
Duplicate of https://github.com/elm-lang/error-message-catalog/issues/15

**Comment by rtfeldman** [comment] 2015-11-24 17:03
Closing as duplicate; feel free to reopen if you disagree!

**Closed by rtfeldman** 2015-11-24 17:03 UTC
