### ISSUE TITLE
Get the typechecker to consider "not really rigid" type variables as not rigid

### ISSUE THREAD

**Issue by TheSeamau5** [elm-lang/error-message-catalog#5] opened 2015-05-11 17:12 UTC
Namely this code:

```elm
f : a -> a
f x = 
  let 
      y : a
      y = x
      
  in y
```

triggers this error:

```
-- TYPE MISMATCH -------------------------------------------------------------- 

This expression is triggering a type mismatch.

Could not unify rigid type variable 'a'. The problem probably
relates to the type variable being shared between two type annotations.
Try commenting out some type annotations and see what happens.

2| 
3|   let 
4|       y : a
5|       y = x
6|       
7|   in y
8| 

To be more specific, as I infer all the types, I am seeing a conflict between
this type:

    a

and this type:

    a
```

I can hazard a guess why the typechecker considers this a type error (it considers the inner `a` to be a different `a` because of the different scope). But, if a beginner sees this, he/she will go: "??!!??? What do you mean `a` is not `a`??!!?? (insert favorite expletives)"

My intuition tells me that this would require a non-trivial modification to the type checker but it would be worth it. Especially for large functions that consist of multiple inner closures, trampolines, nested let-in expressions, etc... where you'd want to add the type annotations at that level too (not just at the outer level).

**Comment by rtfeldman** [comment] 2015-05-11 18:07
I think we've seen people on the mailing list run into this one.

For what it's worth, I think this could be considered a duplicate of wanting the example at the end of https://github.com/evancz/error-message-catalog/issues/4#issue-75059413 to work; if it contextualized each `a`, it wouldn't resemble a bug anymore.

So maybe this is just another motivating example for that (someday) as opposed to its own special case?

**Comment by TheSeamau5** [comment] 2015-05-11 18:44
Here's a concrete example of this from `elm-check`:

```elm
claim : String -> (a -> b) -> (a -> b) -> Investigator a -> Claim
claim name actualStatement expectedStatement investigator =
  Claim name <|
    \numberOfChecks seed ->
      let
          -- originalCounterExample' : Seed -> Int -> Trampoline (Result (a, b, b, Seed, Int) Int)
          originalCounterExample' seed currentNumberOfChecks =
            if currentNumberOfChecks >= numberOfChecks
            then
              Done (Ok numberOfChecks)

            else
              let
                  (value, nextSeed) = Random.generate investigator.generator seed
                  actual    = actualStatement value
                  expected  = expectedStatement value
              in
                  if actual == expected
                  then
                    Continue (\() -> originalCounterExample' nextSeed (currentNumberOfChecks + 1))
                  else
                    Done (Err (value, actual, expected, nextSeed, currentNumberOfChecks + 1))

          -- originalCounterExample : Result (a, b, b, Seed, Int) Int
          originalCounterExample =
            trampoline (originalCounterExample' seed 0)

      in case originalCounterExample of
        Ok numberOfChecks -> Unit <|
          Ok
            { name = name
            , seed = seed
            , numberOfChecks = max 0 numberOfChecks
            }

        Err (originalCounterExample, originalActual, originalExpected, seed, numberOfChecks) ->
          let

              -- shrink : a -> Int -> Trampoline (a, Int)
              shrink counterExample currentNumberOfShrinks =
                let

                    -- shrunkenCounterExamples : List a
                    shrunkenCounterExamples = investigator.shrinker counterExample

                    -- failingShrunkenCounterExamples : List a
                    failingShrunkenCounterExamples =
                      List.filter (\shrunk ->
                        not (actualStatement shrunk == expectedStatement shrunk)
                      ) shrunkenCounterExamples

                in case List.head failingShrunkenCounterExamples of
                  Nothing ->
                    Done (counterExample, currentNumberOfShrinks)

                  Just failing ->
                    Continue (\() -> shrink failing (currentNumberOfShrinks + 1))

              -- minimal : a
              -- numberOfShrinks : Int
              (minimal, numberOfShrinks) =
                trampoline (shrink originalCounterExample 0)

              -- actual : b
              actual    = actualStatement minimal

              -- expected : b
              expected  = expectedStatement minimal

          in
            Unit <|
              Err
                { name = name
                , seed = seed
                , counterExample = toString minimal
                , expected = toString expected
                , actual = toString actual
                , original =
                  { counterExample = toString originalCounterExample
                  , actual    = toString originalActual
                  , expected  = toString originalExpected
                  }
                , numberOfChecks = numberOfChecks
                , numberOfShrinks = numberOfShrinks
                }

```

As you can see, the sheer scale of this function has made me wish that I can actually insert those inner types. So much so that they're there in the source code but commented out. All those closures make it hard to keep track of what variable is of what type (especially in the trampolines). 

You can imagine my joy when I finally got this thing to typecheck. :smile:

**Comment by evancz** [comment] 2015-05-11 18:51
Haskell has the same issue as this, but OCaml does not. So I guess it can be done either way. I am not sure.

@TheSeamau5, why not break the function into smaller parts? I have been moving towards always using `let` in my Haskell code (no `where`) and it is often really helpful to add some top-level helper functions, like in [this file](https://github.com/elm-lang/elm-compiler/blob/master/src/Type/Constrain/Expression.hs). I find that things are quite a bit clearer this way.

**Comment by TheSeamau5** [comment] 2015-05-11 19:25
Something like this?
https://gist.github.com/TheSeamau5/c6ef76fdc215519a24a0

Our opinions may vary on this one, but the thing is that the `claim` function heavily utilizes closures, so you can see how many arguments I have to pass. I personally dislike the broken up version, but I'm open to being convinced otherwise.

**Comment by evancz** [comment] 2016-10-26 23:43
This is nicer in 0.18! Type variables are now shared between with subdefinitions.

**Closed by evancz** 2016-10-26 23:43 UTC
Labels: types
